config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :sales
  resources :users
  root 'members#index' 

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :members
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
  has_many :users, through: :users_hobbies
  has_many :users_hobbies
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :sales_details
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :group
  def self.search(name_kana,select_group)
     Member.where('name_kana LIKE ? AND group_id = ?',
                   "%#{name_kana}%",
                   "#{select_group}")
  end

  def self.search_kana(name_kana)
     Member.where('name_kana LIKE ?',
                   "%#{name_kana}%")
  end

  def self.search_group(select_group)
     Member.where('group_id = ?',
                   "#{select_group}")
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  has_many :sales_details
end

app/models/sales_detail.rb
class SalesDetail < ActiveRecord::Base
  belongs_to :item
  belongs_to :sale

#  def total
#    price * quantity
#  end

end	

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hobbies, through: :users_hobbies
  has_many :users_hobbies

  accepts_nested_attributes_for :hobbies

  def self.search(name, hobby)
    User.joins(:hobbies)
        .order(:id)
        .where('users.name LIKE ? AND hobbies.id = ?',
               "%#{name}%",
               "#{hobby}")
  end

  def self.search_name(name)
    User.joins(:hobbies)
        .distinct
        .order(:id)
        .where('users.name LIKE ?',"%#{name}%")
  end

  def self.search_hobby(hobby)
    User.joins(:hobbies)
        .distinct
        .where('hobbies.id = ?',"#{hobby}")
  end

  def self.result(id)
    User.joins(:hobbies)
        .distinct
        .order(:id)
        .where('users.id = ?',"#{id}")
  end

end

app/models/users_hobby.rb
class UsersHobby < ActiveRecord::Base
  belongs_to :user
  belongs_to :hobby

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def index
    if params[:name_kana] && params[:select_group]
      if !params[:name_kana].empty?
        if !params[:select_group].empty?
          @members = Member.search(params[:name_kana],params[:select_group])
          binding.pry
        else
          @members = Member.search_kana(params[:name_kana])
          binding.pry
        end
      else
        if !params[:select_group].empty?
          @members = Member.search_group(params[:select_group])
          binding.pry
        else
          @members = Member.search_kana(params[:name_kana])
          binding.pry
        end
      end
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @sales = Sale.joins(:sales_details)
        .order(:id)
        .group('sales.id')
        .select('sales.*, SUM(sales_details.price * sales_details.quantity) * 1.08 AS sum')
  end

  def show
    @salesDetails = SalesDetail
        .joins(:item)
        .where( "sale_id = ?","#{params[:id]}" )
        .select('items.*, sales_details.*')
    
    @sale = Sale.joins(:sales_details)
        .order(:id)
        .group('sales.id')
        .where( 'sales.id = ?', "#{params[:id].to_i}")
        .select('sales.*, SUM(sales_details.price * sales_details.quantity) * 1.08 AS sum')
  end
end

app/controllers/sales_details_controller.rb
class SalesDetailsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = []
    #初期表示時ならば何も処理しない。
    if params[:name] && params[:hobby]
      if !params[:hobby].empty?
        if !params[:name].empty?
          #趣味と名前に入力があるのならば以下の処理
          @users = User.search(params[:name],
                                      params[:hobby])
        else
          #趣味のみ入力
          @users = User.search_hobby(params[:hobby])
        end
      else
          #名前のみ入力
          @users = User.search_name(params[:name])
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/sales_details_helper.rb
module SalesDetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marason</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_member.html.erb
<% @group = member.group %>
<tr>
  <td> <%= member.name %> </td>
  <td> <%= member.name_kana %> </td>
  <td> <%= member.mail_address %> </td>
  <td> <%= member.area %> </td>
  <td> <%= @group.name %> </td>
  <td> <%= member.join_date.strftime('%Y/%m/%d') %> </td>
</tr>

app/views/members/index.html.erb
<%= form_tag members_path, method: 'get' do %>
  <div>  
    <div>
      <%= label_tag "名前（カナ）" %>
      <%= text_field_tag :name_kana, params[:name_kana] %>
    </div>
    <div>
      <%= label_tag "グループ" %>
      <%= select_tag("select_group",options_from_collection_for_select(Group.all,:id,:name), :prompt => "-選択してください-") %>
    </div>
    <div>
      <%= submit_tag "検索" %>
    </div>
    <br/>
    <br/>
  </div>
  <% if @members %>
    <div> 検索結果：<%= @members.count %></div>
    <table border="1" cellpadding="5">
      <tr>
        <td>名前（漢字）</td>
        <td>名前（カナ）</td>
        <td>メールアドレス</td>
        <td>拠点</td>
        <td>グループ</td>
        <td>入社年月日</td>
      </tr>
      <%= render @members %>
    </table>
  <% end %>
  <div> <%= link_to("２問目へ", sales_path) %></div>
<% end %>

app/views/sales/_sale.html.erb
<tr>
  <td>
    <%= sale.id %>
  </td> 
  <td>
    <%= sale.custom_name %>
  </td>
  <td>
    <%= sale.staff_name %>
  </td>
  <td>
    <%= sale.sum.to_i %> 円
  </td>
  <td>
    <%= sale.sale_date.strftime('%Y/%m/%d') %>
  </td>
  <td>
    <%= link_to("detail", sale_path(sale.id)) %>
  </td>
</tr>

app/views/sales/index.html.erb
<div>売上一覧：<%= Sale.count %></div>
<table border="1" cellpadding="5">
  <tr>
    <td>売上ID</td>
    <td>顧客名</td>
    <td>弊社担当</td>
    <td>売上合計金額（税込）</td>
    <td>売上日</td>
    <td></td>
  </tr>
    <%=render @sales %>
</table>

app/views/sales/show.html.erb
<h1>売上明細</h1>
<table>
  <tr>
    <td>
      売上ID
    </td>
    <td>
     : 
    </td>
    <td>
      <%= @sale[0].id %> 
    </td>
  </tr>
  <tr>
    <td>
      顧客名
    </td>
    <td>
      :
    </td>
    <td>
      <%= @sale[0].custom_name %>
    </td>
  </tr>
 <tr>
    <td>
      弊社担当
    </td>
    <td>
      :
    </td>
    <td>
      <%= @sale[0].staff_name %>
    </td>
  </tr>
 <tr>
    <td>
      売上金額（税込）
    </td>
    <td>
      :
    </td>
    <td>
      <%= @sale[0].sum.to_i %>円 
    </td>
  </tr>
</table>

<h2>明細</h2>
<table border="1" cellpdding="5">
  <tr>
    <td>
      商品名
    </td>
    <td>
      単価
    </td>
    <td>
      個数
    </td>
    <td>
      計
    </td>
  </tr>
  <%= render @salesDetails %>
</table>
<div>
  <%= link_to("5問目へ", users_path) %>
</div>

app/views/sales_details/_sales_detail.html.erb
<tr>
  <td>
    <% binding.pry %>
    <%= sales_detail.item.name %>
  </td>
  <td>
    <%= sales_detail.item.price %>
  </td>
  <td>
    <%= sales_detail.quantity %>
  </td>
  <td>
    <%= sales_detail.quantity * sales_detail.item.price %>
  </td>
</tr>

app/views/users/_user.html.erb
 <tr>
   <td>
     <%= user.name %>
   </td>
   <td>
     <%= user.mail_address %>
   </td>
   <td>
     <%= user.birthday.strftime('%Y/%m/%d') %>
   </td>
   <td>
     <%= user.hobbies.pluck(:name).join(",") %>
   </td>
 </tr>

app/views/users/index.html.erb
<h1>user_search</h1>
<%= form_tag users_path, method: 'get' do %>
<div>
  <%= label_tag "name" %>
  <%= text_field_tag :name, params[:name] %>
</div>
<div>
  <%= label_tag "hobby" %>
  <%= select_tag :hobby, options_from_collection_for_select(
                            Hobby.all,
                            :id,
                            :name),
                            :include_blank => 'select' %>
</div>
<div>
  <%= submit_tag "search" %>
</div>
  <% end %>
  <% if @users && @users.count != 0 %>
<div>
  <%= @users.count %>
</div>
<div>
  <table border="1" cellpadding="5">
    <tr>
      <td>
       name 
      </td>
      <td>
        mail_address
      </td>
      <td>
        birthday
      </td>
      <td>
        hobbies
      </td>
    </tr>
    <%= render @users %>
  </table>
</div>
<% end %>